const products = [
  {
    id: 1,
    url: require("../assets/images/categories/angularcolouredlogo.webp"),
    name: "Angular",
    category: "Web Frameworks",
    price: 50.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 2,
    url: require("../assets/images/categories/reactjs.jpg"),
    name: "React",
    category: "Web Development",
    price: 40.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 3,
    url: require("../assets/images/categories/reactnativecolor.png"),
    name: "React Native",
    category: "Web Frameworks",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 4,
    url: require("../assets/images/categories/typescript.png"),
    name: "Typescript Mastery",
    category: "Coding Language",
    price: 70.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 5,
    url: require("../assets/images/categories/js2.png"),
    name: "Javascript Mastery",
    category: "Electronics",
    price: 55.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 6,
    url: require("../assets/images/categories/nodejsgray.png"),
    name: "Node Mastery",
    category: "Web Frameworks",
    price: 55.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 7,
    url: require("../assets/images/categories/csharpsquare.png"),
    name: "C#",
    category: "Coding Language",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 8,
    url: require("../assets/images/categories/cppmain.jpg"),
    name: "C++",
    category: "Coding Languauge",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 9,
    url: require("../assets/images/categories/python.webp"),
    name: "Python",
    category: "Coding Languauge",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 10,
    url: require("../assets/images/categories/prisma.png"),
    name: "Prisma",
    category: "Web Frameworks",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },
  {
    id: 11,
    url: require("../assets/images/categories/djangologo.png"),
    name: "Django",
    category: "Web Frameworks",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },

  {
    id: 12,
    url: require("../assets/images/categories/nextjs1.webp"),
    name: "NextJS",
    category: "Watches",
    price: 120.0,
    quantity: 0,
    isLiked: false,
  },
];

const exportSliderImages = [
  {
    body: { image: require("../assets/images/categories/waiter.jpg") },
  },
  { body: { image: require("../assets/images/categories/coffeecup.jpg") } },
  {
    body: { image: require("../assets/images/categories/coffeewithteam.jpg") },
  },
  {
    body: {
      image: require("../assets/images/categories/cookies.jpg"),
    },
  },
  { body: { image: require("../assets/images/categories/cookies.jpg") } },
  { body: { image: require("../assets/images/categories/team.png") } },
];
